"""email foreign key

Revision ID: f28fb3b032b3
Revises: e00161b2f003
Create Date: 2023-11-21 21:43:13.543867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f28fb3b032b3'
down_revision: Union[str, None] = 'e00161b2f003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('edited_by_email', sa.String(), nullable=True))
    op.create_foreign_key('fk_image_user_email', 'image', 'user', ['edited_by_email'], ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_image_user_email', 'image', type_='foreignkey')
    op.drop_column('image', 'edited_by_email')
    # ### end Alembic commands ###
