"""Changes

Revision ID: 54912fe9b6b4
Revises: 32a49f838f30
Create Date: 2023-11-21 21:14:52.008464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '54912fe9b6b4'
down_revision: Union[str, None] = '32a49f838f30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('surname', sa.String(), nullable=False),
                    sa.Column('middle_name', sa.String(), nullable=False),
                    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
                    sa.Column('role_id', sa.Integer(), nullable=True),
                    sa.Column('hashed_password', sa.String(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_superuser', sa.Boolean(), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('image', sa.Column('edited_by_tmp', sa.Integer()))
    op.execute('UPDATE image SET edited_by_tmp = edited_by::integer')
    op.drop_column('image', 'edited_by')
    op.alter_column('image', 'edited_by_tmp', new_column_name='edited_by', existing_type=sa.Integer())
    op.create_foreign_key('fk_image_user_id', 'image', 'user', ['edited_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_image_user_id', 'image', type_='foreignkey')
    op.alter_column('image', 'edited_by',
                    existing_type=sa.Integer(),
                    type_=sa.VARCHAR(),
                    existing_nullable=True)
    op.drop_table('user')
    # ### end Alembic commands ###
