"""add fio user

Revision ID: ab3f368ce104
Revises: cf9ce9940d3f
Create Date: 2023-12-03 20:58:17.590831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab3f368ce104'
down_revision: Union[str, None] = 'cf9ce9940d3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'image', ['id'])
    op.add_column('user', sa.Column('name', sa.String(), nullable=False))
    op.add_column('user', sa.Column('surname', sa.String(), nullable=False))
    op.add_column('user', sa.Column('middle_name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'middle_name')
    op.drop_column('user', 'surname')
    op.drop_column('user', 'name')
    op.drop_constraint(None, 'image', type_='unique')
    # ### end Alembic commands ###
